apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
  namespace: voting
# spec:
#   type: ClusterIP
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     name: result-app-pod
#     app: demo-voting-app
spec:
  type: LoadBalancer  # Change the service type to LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app
